Feat/modularization
RonasIT/terraform-google-project-factory pull request #2
Opened 2022-11-03 08:44 UTC by eleonov

2022-11-03 09:02 UTC, astorozhevsky approved these changes

2022-11-30 15:51 UTC, eleonov commented
@astorozhevsky please check after fixes

2022-12-01 08:13 UTC, astorozhevsky requested changes

2022-12-01 08:13 UTC, astorozhevsky commented on main.tf
> +  name    = "${var.project_name}-${var.environment_name}-nginx"
I suggest renaming this to `${var.project_name}-${var.environment_name}-nginx-ingress-controller`

2022-12-01 08:13 UTC, astorozhevsky commented on modules/cloud-sql/output.tf
> +  description = "The password of the defaule user to access database"
```suggestion
  description = "The password of the default user to access database"
```

2022-12-01 08:13 UTC, astorozhevsky commented on modules/cloud-sql/variables.tf
> +  description = "The region of the cluster"
the same description as above

2022-12-01 08:24 UTC, astorozhevsky approved these changes

2022-12-01 08:24 UTC, merged